version: '3'   
services:
  frontend:
    build: frontend
    
    ports:
      - 3000:3000
  
    stdin_open: true
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      -  authentification

  authentification:
    build: backend/auth
    ports:
       - 3001:3001
    
    container_name: authentification
    volumes:
      - ./backend/auth:/ap