apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    app: deploy-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-auth

  template:
    metadata:
      labels:
        app: deploy-auth
    spe