openapi: 3.0.1
info:
  title: Blockchain GPT Plugin
  description: A plugin that allows users to interact with and manage their blockchain environments through natural language commands.
  version: 'v1'
servers:
- url: PLUGIN_HOSTNAME
paths:
  /execute-command:
    post:
      operationId: executeCommand
      summary: Execute a command in the blockchain environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executeCommandRequest'
      responses:
        "200":
          description: OK
          content:
            application/j